name: BL_TEST
run-name: ${{ github.actor }} has triggered CD process.
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Compile and Pack Node.js
      run: |
        npm install
        PACKAGE_FILENAME=$(npm pack)
        echo "PACKAGE_FILENAME=$PACKAGE_FILENAME" >> $GITHUB_ENV

    - name: Initiate Deployment To Azure VM
      id: bastion
      run: |
        set x
        cat <<EOF > ~/vm.pem
        ${{ secrets.SSH_PRIVATE_KEY }}
        EOF
        chmod 600 ~/vm.pem
        scp -i ~/vm.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PACKAGE_FILENAME ${{ secrets.SSH_USER_NAME }}@${{ secrets.BASTION_IP }}:/home/blAzureUser/blProject
